name: ci

on: push

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/latest/download/install
          extra_nix_config: experimental-features = flakes nix-command

      - name: Set up cachix
        uses: cachix/cachix-action@v8
        with:
          name: nix-community
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Build with nix
        run: |
          nix flake update --{recreate,commit}-lock-file
          pkgs=(.#{{minimal,default,complete,latest}.toolchain,rust-analyzer{,-vscode-extension}})
          nix build "${pkgs[@]}"
          nix build --override-input nixpkgs github:nixos/nixpkgs/nixpkgs-unstable "${pkgs[@]}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: main
