name: update

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/latest/download/install
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: experimental-features = flakes nix-command

      - name: Update toolchains
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          nix develop -c ./update
          if [ -n "$(git diff)" ]; then
            git commit -am "update toolchains"
          fi

      - name: Update lock file
        run: nix flake update --{recreate,commit}-lock-file

      - name: Set up cachix
        uses: cachix/cachix-action@v8
        with:
          name: fenix
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build with nix
        run: |
          nix-build packages.nix -A minimal -A default -A complete \
            --arg pkgs "import <nixpkgs> {}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: main
